- hosts: nodes
  become: true
  tasks:
    - apt:
       name: docker,docker-engine,docker.io,containerd,runc
       state: absent
       update_cache: yes
    - apt:
       name: apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common
       state: present
       update_cache: yes
    - name: command run
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    - apt:
       name: apt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common
       state: present
       update_cache: yes
    - apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       update_cache: yes
    - apt:
       name: docker-ce,docker-ce-cli,containerd.io
       state: present
       update_cache: yes
    - name: make devops user decoker ready
      shell: usermod -aG docker devops
